# Generated by Django 2.0 on 2019-08-15 03:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voicereq',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='voicereq',
            name='record_end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='voicereq',
            name='record_start_time',
            field=models.DateTimeField(),
        ),
    ]
