# Generated by Django 2.0 on 2019-08-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20190815_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicereq',
            name='record_type',
            field=models.SmallIntegerField(default=2),
            preserve_default=False,
        ),
    ]
