# Generated by Django 2.0 on 2019-08-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_voicereq_record_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voicereq',
            name='record_type',
            field=models.SmallIntegerField(max_length=1),
        ),
    ]
