# Generated by Django 2.0 on 2019-08-20 07:50

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20190819_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('api_key', models.CharField(default=catalog.models.generateUUID, editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'db_table': 'api_key',
            },
        ),
    ]
