# Generated by Django 2.0 on 2019-08-20 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='status',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voicereq',
            name='record_type',
            field=models.SmallIntegerField(),
        ),
    ]
