# Generated by Django 2.2.4 on 2019-08-27 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20190820_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voicereq',
            name='record_end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='voicereq',
            name='record_start_time',
            field=models.TimeField(),
        ),
    ]
